MAX_RESULTS = 100
MAX_RECRAWL_ROUNDS = 4
SEMANTIC_RERANK_ENABLED = True
MIN_COMBINED_RELEVANCE = 0.25
TOTAL_LINK_TARGET = 200
MAX_SEMANTIC_CANDIDATES = 200
STRICT_FOCUS_HIGH_SCORE = 0.65
MIN_OUTPUT_LINKS = 10
